services:
  postgres:
    image: mongo:6.0.5
    container_name: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
  ghostorange:
    image: gotracer
    container_name: gotracer
    build: .
    env_file:
      - ./ghostcfg.env
    depends_on:
      mongo:
        condition: service_healthy
  
volumes:
  psql_data:
