services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 5s
      timeout: 5s
      retries: 5
  ghostorange:
    image: gotracer
    container_name: gotracer
    build: .
    ports:
      - 8080:8080
    depends_on:
      mongo:
        condition: service_healthy
  
volumes:
  psql_data:
